import chai: expect
import ../lib/HashRing

describe('HashRing', () ->
  instance = undefined

  beforeEach(() ->
    instance = new HashRing()
  )

  describe('.init(hasher)', () ->
    it('should create an instance', () ->
      expect(instance).to.be.ok
    )
  )

  describe('.add(node, weight)', () ->
    it('should add the node to the ring', () ->
      instance.add({})
      expect(Object.size(instance.ring)).to.equal(1)
      expect(instance.keys.length).to.equal(1)

      instance.add({ id: 'some-node' })

      expect(Object.size(instance.ring)).to.equal(2)
      expect(instance.keys.length).to.equal(2)
    )

    it('should sort the key list', () ->
      instance.add({ id: 'a-node' })
      instance.add({ id: 'some-node' })
      keys = instance.keys
      instance.keys.sort()
      expect(instance.keys).to.equal(keys)
    )
  )

  describe('.createKey(node)', () ->
    it('should return the same hash for same value', () ->
      expect(instance.createKey({})).to.equal(instance.createKey({}))
      expect(instance.createKey({ a: 'hi there' })).to.equal(instance.createKey({ a: 'hi there' }))
    )
    it('should return diffeent hash for same value', () ->
      expect(instance.createKey({})).to.not.equal(instance.createKey({ a: 'hi there' }))
    )
  )
)
