import sha1
import ./ObjectUtils
export HashRing

class HashRing
  defaultNodeWeight: 200
  keys: []
  ring: {}

  init: (hasher) ->
    @hasher = hasher

  add: (node, weight) ->
    weight = weight or @defaultNodeWeight
    key = @createKey(node)
    @ring[key] = node
    @keys.push(key)
    @keys.sort()

  remove: () ->
    throw 'NotImplemented'

  createKey: (node) ->
    return sha1(JSON.stringify(node))
